version: "3.8"

services:
  mcp-browser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-browser
    shm_size: "2gb"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - RUN_TESTS=${RUN_TESTS:-false}
      - DISPLAY=:99
      - DEBUG=pw:api,pw:browser
    ports:
      - "${MCP_PORT:-8000}:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
      - ./requirements-test.txt:/app/requirements-test.txt
      - /var/run/docker.sock:/var/run/docker.sock
      - playwright_cache:/root/.cache/ms-playwright
    networks:
      - default
      - mcp-browser-internal
      - mcp-browser-external
      - mcp-browser-monitoring
    security_opt:
      - apparmor=mcp-browser
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 1024
      net.ipv4.tcp_synack_retries: 2
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  default:
    driver: bridge
  mcp-browser-internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
  mcp-browser-external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
  mcp-browser-monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

volumes:
  playwright_cache:
