services:
  mcp-browser:
    build: .
    image: neoforge-dev/mcp-browser:latest
    environment:
      - MCP_SECRET=${MCP_SECRET}
      - SERVER_PORT=8000
      - DISPLAY=:99
    security_opt:
      - apparmor=mcp-browser
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 2G
    ports:
      - "7665:8000"
    volumes:
      - ./src:/app/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
